#!/usr/bin/env sh

absolute_path() {
  echo "$(dirname "$(readlink -e -- "$1")")"
}

# Get the path to the dotfile repo
repo_location=$(absolute_path "$0")

while getopts ':fdh' opts; do
  case $opts in
    f)
      force=true
      ;;
    d)
      echo "$repo_location"
      ;;
    h)
      help=true
      ;;
    --)
      break
      ;;
    *)
      echo "Invalid option provided"
      echo "Exiting"
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

if [ "$help" = true ]; then
  echo "Usage:
  df [options]

Options:
  --                    Treat everything after this as a filename

  -f                    overwrite the existing files if they exist"
  exit
fi
