#!/usr/bin/env sh

help() {
  echo "Usage:
  df add                Add a file to the dots repo
  df remove             Remove a file from the dots repo
  df link               symlink the files
  df unlink             remove the symlink
  df help               Print this page then exit

Options:
  -h                    Print the help. Can be used after an above option"
}

add() {
  echo add
}

remove(){
  echo remove
}

link() {
  echo link
}

unlink() {
  echo unlink
}

absolute_path() {
  dirname "$(readlink -e -- "$1")"
}

# Get the path to the dotfile repo
repo_location=$(absolute_path "$0")

while getopts ':dh' opts; do
  case $opts in
    d)
      echo "$repo_location"
      ;;
    h)
      print_help
      exit
      ;;
    *)
      echo "Invalid option provided"
      echo "Exiting"
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

cmd="$1"
if command -V "$cmd" 2> /dev/null | grep -qwi function; then
  shift
  $cmd "$@"
fi
