#!/usr/bin/env sh

print_help() {
  echo "Usage:
  df add                Add a file to the dots repo
  df remove             Remove a file from the dots repo
  df link               symlink the files
  df unlink             remove the symlink

Options:
  -h                    Print this page then exit"
}

absolute_path() {
  echo "$(dirname "$(readlink -e -- "$1")")"
}

# Get the path to the dotfile repo
repo_location=$(absolute_path "$0")

while getopts ':dh' opts; do
  case $opts in
    d)
      echo "$repo_location"
      ;;
    h)
      print_help
      exit
      ;;
    *)
      echo "Invalid option provided"
      echo "Exiting"
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

echo "$@"
