#!/usr/bin/env sh
#  ______   _______ _________ _______ 
# (  __  \ (  ___  )\__   __/(  ____ \
# | (  \  )| (   ) |   ) (   | (    \/
# | |   ) || |   | |   | |   | (_____ 
# | |   | || |   | |   | |   (_____  )
# | |   ) || |   | |   | |         ) |
# | (__/  )| (___) |   | |   /\____) |
# (______/ (_______)   )_(   \_______)
#
# Original file created by Rory Nesbitt
# https://github.com/RoryNesbitt/DotFiles/blob/master/dots
# Steal this and put it in your dotfile repo

IFS=":"

####### Meta Functions #########

help() {
  case $1 in
    "store")
      echo "Usage:
  $script_name store <files>
                        Store files in the dotfile repo
                        This will take a file, or all files
                        under a directory, from anywhere under
                        \$HOME and move it to the dotfile repo,
                        leaving a symlink in it's place.

Options:
  -h                    Help: Print this page and exit
  -D                    Dryrun: Don't actually change anything
  -f                    Force: Overwrite existing files
  "
      ;;
    "remove")
      echo "Usage:
  $script_name remove <files>
                        Remove files from the dotfile repo
                        This will delete files, or directories,
                        from the dotfile repo with the option to either
                        also delete the symlinks or to replace
                        them with the original file

Options:
  -y                    Keep local files, replacing the symlinks
  -n                    Remove the symlink, not keeping any copy of the file
  -h                    Help: Print this page and exit
  -D                    Dryrun: Don't actually change anything
  -f                    Force: Overwrite existing files
                        (Force is only useful when keeping local files)
  "
      ;;
    "link")
      echo "Usage:
  $script_name link <files>
                        Symlink files that are in the dotfile repo
                        Create symlinks under \$HOME for each
                        of the files specified from the dotfile repo

Options:
  -h                    Help: Print this page and exit
  -D                    Dryrun: Don't actually change anything
  -f                    Force: Overwrite existing files
  "
      ;;
    "unlink")
      echo "Usage:
  $script_name unlink <files>
                        Remove the symlink to the files
                        Removes the symlink but doesn't touch
                        the dotfile repo copy of the file

Options:
  -h                    Help: Print this page and exit
  -D                    Dryrun: Don't actually change anything
  -f                    Force: Don't check it's actually a symlink, just
                        remove it
  "
      ;;
    "clean")
      echo "Usage:
  $script_name clean
                        Checks \$HOME for dead symlinks to the dotfile repo
                        Removes any symlinks under \$HOME that point
                        into the dotfile repo but whose target no longer exists

Options:
  -h                    Help: Print this page and exit
  -D                    Dryrun: Don't actually remove anything
  -q                    Quiet: Don't show the symlinks that are being removed
  -v                    Verbose: override Quiet
  "
  ;;
    "fix")
      echo "Usage:
  $script_name fix
                        Converts relative symlinks to absolute
                        Checks for any symlinks under \$HOME that point
                        relatively to the dotfile repo and replaces them with
                        absolute symlinks
                        This is slow but lets $script_name clean work much faster
                        by not having to check relative symlinks every time
                        Symlinks created by $script_name will be absolute, this is a
                        one time fix

Options:
  -h                    Help: Print this page and exit
  -D                    Dryrun: Don't actually change anything
  -q                    Quiet: Don't show the symlinks that are being changed
  -v                    Verbose: override Quiet
  "
  ;;
    "help" | "-h")
      echo "I need help too"
      ;;
    "pull")
      echo "Usage:
  $script_name pull <args>
                        Update the dotfile repo and clean dead symlinks
                        Runs git pull on the dotfile repo, then cleans
                        any dead symlinks.
                        (equivelent to git -C \$repo_location; $script_name clean)

Options:
  -D                    Dryrun: Show which symlinks would be removed
                        without pulling or deleting anything
                        Uses git fetch
  <args>                All arguments are passed to git pull only.
  "
      ;;
    *)
      echo "Usage:
  $script_name store            Store files in the dotfile repo
  $script_name remove           Remove files from the dotfile repo
  $script_name link             Symlink files that are in the dotfile repo
  $script_name unlink           Remove the symlink to the files
  $script_name clean            Remove deal symlinks
  $script_name fix              Convert relative symlinks to absolute
  $script_name help             Print this page then exit

Git Wrappers
  $script_name <cmd>            Runs git command on the dotfile repo
  $script_name pull             Also removes dead symlinks

Options:
  -h                    Print the help for a command
                        use <cmd> -h for more options
  -v                    Show verbose output
  -D                    Dryrun only
  "
      ;;
  esac
}

# shellcheck disable=SC2120
force() {
  echo "Force will disable all saftey checks."
  echo "It is not recommended unless completely necessary."
  echo "Are you sure? [yN]"
  read -r yn
  case $yn in
    [Yy] | [Yy][Ee][Ss] ) force=true ;;
    "" | [Nn] | [Nn][Oo]) echo "Good choice :)"; exit ;;
    *                   ) err "Option not recognised"; exit 1 ;;
  esac
  [ "$@" ] && run_cmd "$@"
}

# Called by `dots verbose cmd` - equivelent to -v flag
verbose() {
  get_wordy=true
  run_cmd "$@"
}

####### Subcommand Functions #########

store() {
  while getopts ':hDvf' opts; do
    case $opts in
      h) help store; exit ;;
      D) dryrun=true ;;
      v) get_wordy=true ;;
      f) force ;;
      *) err "Invalid option provided"; exit 1 ;;
    esac
  done
  shift $((OPTIND-1))

  for file in "$@"
  do
    if [ ! -e "$file" ] && [ ! -L "$file" ]; then # doesn't exist
      err "$file not found"
      continue
    fi
    path=$(path_from_home "$file")
    if [ "$path" = false ]; then
      err "$file is outwith \$HOME"
      continue
    fi
    if [ -d "$file" ]; then # directory
      file=$(walk_dir "$(realpath -s "$file")")
    fi

    for f in $file; do
      path=$(path_from_home "$f")

      if [ "$force" = true ] && [ -e "$repo_location$path" ]; then
        [ ! "$dryrun" = true ] && rm "$repo_location$path"
      elif [ -f "$f" ] && [ -e "$repo_location$path" ]; then # file
        v_echo "$path has already been stored. Overwrite it with -f or replace local with link"
        continue
      fi

      if [ "$dryrun" = true ]; then
        q_echo "Dryrun: would store \$HOME$path"
      else
        mkdir -p "$(dirname "$repo_location$path")"
        mv "$f" "$repo_location$path"
        ln -s "$repo_location$path" "$HOME$path"
        v_echo "Stored \$HOME$path"
      fi
    done
  done
}

remove(){
  while getopts ':hDvfyn' opts; do
    case $opts in
      h) help remove; exit ;;
      D) dryrun=true ;;
      v) get_wordy=true ;;
      f) force ;;
      y) keep_local=true ;;
      n) keep_local=false ;;
      *) err "Invalid option provided"; exit 1 ;;
    esac
  done
  shift $((OPTIND-1))

  if [ "$keep_local" = "" ]; then
    echo "Do you want to keep the local file? [Yn]"
    read -r yn
    case $yn in
      "" | [Yy] | [Yy][Ee][Ss]) keep_local=true ;;
      [Nn] | [Nn][Oo]         ) keep_local=false ;;
      *                       ) err "Option not recognised"; exit 1 ;;
    esac
  fi

  for file in "$@"
  do
    unset dir
    if [ ! -e "$file" ] && [ ! -L "$file" ]; then # doesn't exist
      err "$file not found"
      continue
    fi
    if [ -d "$file" ]; then # directory
      dir="$file"
      file=$(walk_dir "$(realpath -s "$file")")
    fi

    for f in $file; do
      path=$(path_from_home "$f")
      if [ "$path" = false ]; then
        err "$f is outwith \$HOME"
        continue
      elif [ ! -e "$HOME$path" ]; then
        err "$f is not in your \$HOME"
        continue
      elif [ ! -e "$repo_location$path" ]; then
        err "$f is not in the dotfile repo"
        continue
      fi
      if [ "$keep_local" = true ] && [ "$force" = true ] || [ -L "$HOME$path" ]; then
        [ ! "$dryrun" = true ] && rm "$HOME$path"
      elif [ "$keep_local" = true ]; then
        err "$HOME$path is not a symlink. Remove repo copy with -n or overwrite local with -f"
        continue
      fi
      if [ "$dryrun" = true ]; then
        q_echo "Dryrun: would remove $path"
      elif [ "$keep_local" = true ]; then
        mv "$repo_location$path" "$HOME$path"
        v_echo "Removed $path"
      else
        rm "$repo_location$path"
        v_echo "Removed $path"
      fi
    done
    if [ ! "$dryrun" = true ] && [ "$repo_location" != "" ] && [ "$dir" != "" ]; then
      # shellcheck disable=SC2115
      [ -d "$repo_location/$dir" ] && rm -rf "$repo_location/$dir"
      if [ ! "$keep_local" = true ] && [ -d "$HOME/$dir" ]; then
        # shellcheck disable=SC2115
        rm -rf "$HOME/$dir"
      fi
    fi
  done
}

link() {
  while getopts ':hDvf' opts; do
    case $opts in
      h) help link; exit ;;
      D) dryrun=true ;;
      v) get_wordy=true ;;
      f) force ;;
      *) err "Invalid option provided"; exit 1 ;;
    esac
  done
  shift $((OPTIND-1))

  for file in "$@"
  do
    path=$(path_from_home "$file")
    if [ "$path" = false ]; then
      err "$file is outwith \$HOME"
      continue
    fi
    file="$repo_location$path"
    if [ ! -e "$file" ] && [ ! -L "$file" ]; then # doesn't exist
      err "$file not found"
      continue
    fi
    if [ -d "$file" ]; then # directory
      file=$(walk_dir "$file") # safe, already absolute
    fi

    for f in $file; do
      path=$(path_from_home "$f")

      if [ ! -e "$repo_location$path" ]; then
        err "$f is not in the dotfile repo"
        continue
      elif [ "$force" = true ]; then
        [ ! "$dryrun" = true ] && rm -f "$HOME$path"
      elif [ -L "$HOME$path" ]; then
        v_echo "$f is already linked"
        continue
      elif [ -f "$f" ] && [ -e "$HOME$path" ]; then
        err "$path already exists. Overwrite it with -f or replace stored copy with store -f"
        continue
      fi

      if [ "$dryrun" = true ]; then
        q_echo "Dryrun: would link \$HOME$path"
      else
        mkdir -p "$(dirname "$HOME$path")"
        ln -s "$repo_location$path" "$HOME$path"
        v_echo "Linked \$HOME$path"
      fi
    done
  done
}

unlink() {
  while getopts ':hDvf' opts; do
    case $opts in
      h) help unlink; exit ;;
      D) dryrun=true ;;
      v) get_wordy=true ;;
      f) force ;;
      *) err "Invalid option provided"; exit 1 ;;
    esac
  done
  shift $((OPTIND-1))

  for file in "$@"
  do
    unset dir
    if [ ! -e "$file" ] && [ ! -L "$file" ]; then # doesn't exist
      err "$file not found"
      continue
    fi
    if [ -d "$file" ]; then # directory
      dir="$file"
      file=$(walk_dir "$(realpath -s "$file")")
    fi

    for f in $file; do
      path=$(path_from_home "$f")
      if [ "$path" = false ]; then
        err "$f is outwith \$HOME"
        continue
      elif [ ! -e "$repo_location$path" ]; then
        err "$f is not in the dotfile repo"
        continue
      fi
      if [ "$force" = true ] || [ -L "$HOME$path" ]; then
        [ ! "$dryrun" = true ] && rm "$HOME$path"
      else
        err "$HOME$path is not a symlink. Overwrite local with -f"
        continue
      fi
      if [ "$dryrun" = true ]; then
        q_echo "Dryrun: would unlink $path"
      else
        cp "$repo_location$path" "$HOME$path"
        v_echo "Unlinked $path"
      fi
    done
  done
}

clean() {
  while getopts ':hDvq' opts; do
    case $opts in
      h) help clean; exit ;;
      D) dryrun=true ;;
      v) get_wordy=true ;;
      q) be_quiet=true ;;
      *) err "Invalid option provided"; exit 1 ;;
    esac
  done

  find "$HOME" -type l -lname "$repo_location*" 2>/dev/null | while IFS= read -r symlink; do
    if [ ! -e "$symlink" ]; then
      if [ "$dryrun" = true ]; then
        q_echo "Dryrun: would remove dead link ~${symlink#"$HOME"}"
      else
        rm "$symlink"
        q_echo "Removed dead link ~${symlink#"$HOME"}"
      fi
    fi
  done
}

fix() {
  while getopts ':hDvq' opts; do
    case $opts in
      h) help fix; exit ;;
      D) dryrun=true ;;
      v) get_wordy=true ;;
      q) be_quiet=true ;;
      *) err "Invalid option provided"; exit 1 ;;
    esac
  done

  find "$HOME" -path "$repo_location" -prune -o -type l 2>/dev/null | while IFS= read -r symlink; do
    target=$(readlink "$symlink")
    case $target in
      /*) continue ;; # already absolute
    esac

    # resolve relative target to absolute
    absolute="$(readlink -f "$symlink")"
    case $absolute in
      "$repo_location"/*)
        if [ "$dryrun" = true ]; then
          q_echo "Dryrun: would fix ~${symlink#"$HOME"}: $target -> $absolute"
        else
          rm "$symlink"
          ln -s "$absolute" "$symlink"
          q_echo "Fixed ~${symlink#"$HOME"}: $target -> $absolute"
        fi
        ;;
    esac
  done
}

####### Git Wrapper Functions #########

pull() {
  [ "$1" = "-D" ] &&  dryrun=true && shift 1 
  if [ "$dryrun" = true ]; then
    q_echo "Dryrun: fetching remote changes"
    git -C "$repo_location" fetch
    tmp=$(mktemp)
    git -C "$repo_location" diff --name-only --diff-filter=D HEAD FETCH_HEAD > "$tmp"
    while IFS= read -r f; do # 'IFS= ' don't split, 'read -r f' read each line without escaping as $f
      symlink="$HOME/$f"
      if [ -L "$symlink" ]; then
        q_echo "Dryrun: would remove dead symlink $symlink"
      fi
    done < "$tmp"
    rm "$tmp"
  else
    git -C "$repo_location" pull "$@"
    clean -q
  fi

}

####### Helper Functions #########

v_echo() {
  [ "$get_wordy" = true ] && echo "$@"
}

q_echo() {
  if [ ! "$be_quiet" = true ] || [ "$get_wordy" = true ]; then
    echo "$@"
  fi
}

err() {
  printf '\033[31merror:\033[0m %s\n' "$@" >&2
}

is_ignored() {
  found=false
  for i in $ignoreList; do
    case "$1" in
      *"/." | *"/.." | *"/*" | "$repo_location/$script_name" | "$repo_location$i" | "$repo_location/$i")
        found=true
        break
        ;;
    esac
  done
  $found
}

walk_dir() {
  for g in "/.*" "/*"; do
    for pathname in "$1"$g; do
      if is_ignored "$pathname"; then
        continue
      elif [ -d "$pathname" ]; then
        walk_dir "$pathname"
      else
        printf '%s:' "$pathname"
      fi
    done
  done
}

path_from_home() {
  absolute="$(realpath -s "$1")"
  [ "$absolute" = "" ] && absolute="$1"
  case $absolute in
    "$repo_location"*) echo "${absolute#"$repo_location"}" ;;
    "$HOME"*         ) echo "${absolute#"$HOME"}" ;;
    *                ) echo false ;;
  esac
}

run_cmd() {
  cmd="$1"
  if command -V "$cmd" 2> /dev/null | grep -qwi function; then
    shift 1
    $cmd "$@"
  elif [ "$cmd" ]; then
    git -C "$repo_location" "$@"
  else
    help
  fi
}

####### END OF FUNCTIONS #########

# Get the path to the dotfile repo
repo_location=$(dirname "$(realpath "$0")")
script_name=$(basename "$0")

# Build the ignore list
ignoreList=".git:.gitignore:.dotignore:.dotsignore:README.md:LICENSE"
[ -f "$repo_location/.dotignore" ] && ignoreList="$ignoreList:$(tr '\n' ':' < "$repo_location/.dotignore")"
[ -f "$repo_location/.dotsignore" ] && ignoreList="$ignoreList:$(tr '\n' ':' < "$repo_location/.dotsignore")"

while getopts ':dDfvh' opts; do
  case $opts in
    d) echo "$repo_location"; exit ;;
    D) dryrun=true ;;
    f) force ;;
    v) get_wordy=true ;;
    h) shift; help "$@"; exit ;;
    *) err "Invalid option provided"; exit 1 ;;
  esac
done
shift $((OPTIND-1))

run_cmd "$@"
