#!/usr/bin/env sh

help() {
  #TODO: help for each command
  echo "Usage:
  dots add              Add a file to the dots repo
  dots remove           Remove a file from the dots repo
  dots link             Symlink the files
  dots unlink           Remove the symlink
  dots help             Print this page then exit

Options:
  -h                    Print the help. Can be used after an above option"
}

add() {
  echo add
}

remove(){
  echo remove
}

link() {
  echo link
}

unlink() {
  echo unlink
}

directory_path() {
  dirname "$(readlink -e -- "$1")"
}

path_from_home() {
  absolute="$(readlink -e -- "$1")"
  case $absolute in
    "$HOME"*)
      echo "${absolute#"$HOME"}"
      ;;
    *)
      echo false
      ;;
  esac

}

# Get the path to the dotfile repo
repo_location=$(directory_path "$0")

while getopts ':dfvh' opts; do
  case $opts in
    d)
      echo "$repo_location"
      ;;
    f)
      force ""
      ;;
    v)
      verbose ""
      ;;
    h)
      help
      exit
      ;;
    *)
      echo "Invalid option provided"
      echo "Exiting"
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

force() {
  echo "Force will disable all saftey checks."
  echo "It is not recommended unless completely necessary."
  echo "Are you sure? [yN]"
  read -r yn
  case $yn in
    [Yy] | [Yy][Ee][Ss] )
      force=true
      ;;
    *)
      echo "Good choice :)"
      exit
      ;;
  esac
  run_cmd "$@" # to let the function be called by name, e.g. dots force add ..
}

verbose() {
  get_wordy=true
  run_cmd "$@"
}

run_cmd() {
  cmd="$1"
  if command -V "$cmd" 2> /dev/null | grep -qwi function; then
    shift 1
    $cmd "$@"
  fi
}

run_cmd "$@"
