#!/bin/sh

if [ $# = 1 ]; then
    if [ $1 = 'w' ]; then
        session='work'
    elif [ $1 = 'ww' ]; then
        session='work-website'
	else
	session=$1
    fi

    if ! tmux has-session -t $session 2> /dev/null; then
	if [ $session = 'work' ]; then
		tmux new -s $session -d -c ~/Documents/work
		tmux new-window -t work:2
		tmux split-window -h -t work:2
		tmux send-keys -t work:1 'nvim .' Enter
		tmux send-keys -t work:2.1 ./start
		tmux select-window -t work:1
	elif [ $session = 'work-website' ]; then
		tmux new -s $session -d -c ~/Documents/work-website
		tmux send-keys -t work-website:1 './home.sh' Enter
	elif [ $session = 'scripts' ]; then
		tmux new -s $session -d -c ~/.bin
		tmux send-keys -t scripts 'nvim .' Enter
	else
		tmux new -s $session -d
	fi  # if $session is 'x'
    fi  # has-session work

    if [ "$TMUX" = "" ]; then
        tmux attach-session -t $session
    else
        tmux switch-client -t $session
    fi
fi


