#!/usr/bin/env sh

dir=$1
if [ ! -d "~/.config/$dir" ] && [ ! -f "~/.config/$dir" ] && [ $(command -v fzf) ]; then
  dir=$(\ls -1 ~/.config/ | fzf --preview="ls -lh --color=always ~/.config/{}" --preview-window=right:70%:wrap --bind=ctrl-f:page-down,ctrl-b:page-up --height=100% --border --prompt="Config: ")
  if [ -z "$dir" ]; then
    exit 1
  fi
fi

if [ $(command -v tmux) ]; then
  tm config $dir
else
  $EDITOR ~/.config/$dir
fi
