#!/bin/sh

if [ $# = 0 ]; then
  tmux list-sessions
  exit 0
fi

if [ "$1" = config ]; then
  session='conf-'$2
else
  session=$1
fi
shift

if ! tmux has-session -t "$session" 2>/dev/null; then
  case "$session" in
  'update')
    tmux new -s "$session" -d "fullUpdate; read key"
    ;;
  'notes')
    tmux new -s "$session" -d "${VISUAL:-${EDITOR:-vi}}"
    ;;
  'scripts')
    tmux new -s "$session" -d -c ~/.local/scripts "${VISUAL:-${EDITOR:-vi}}" "$@"
    ;;
  'conf-'*)
    tmux new -s "$session" -d -c ~/.config/"$1" "${VISUAL:-${EDITOR:-vi}}"
    ;;
  *)
    in_list() {
      printf '%s\n' "$2" | grep -qx "$1"
    }
    if in_list "$session" "$(
      for d in "$HOME"/Documents/*/; do
        [ -d "$d" ] && basename "$d"
      done
    )"; then # session is a directory in Documents
      tmux new -s "$session" -d -c "$HOME/Documents/$session" "$@"

    elif in_list "$session" "$(
      awk '/^Host /{print $2}' "$HOME/.ssh/config"
    )"; then # session is an SSH host
      tmux new -s "$session" -d "ssh $session $*; [ \$? -eq 255 ] && read key"

    else # regular named session
      tmux new -s "$session" -d "$@"
    fi
    ;;
  esac
fi # has-session

if [ -z "$TMUX" ]; then
  tmux attach-session -t "$session"
else
  tmux switch-client -t "$session"
fi # if $TMUX

