#!/bin/sh
cp $HOME/.config/zsh/device.zsh $HOME/tmp

rm -rf $HOME/.cfg

alias config="git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME"
git clone --bare git@github.com:RoryNesbitt/DotFiles.git $HOME/.config/dotfiles/
config checkout --force
config push --set-upstream origin master
config config --local status.showUntrackedFiles no
config update-index --skip-worktree $HOME/.config/zsh/device.zsh

mv $HOME/tmp $HOME/.config/zsh/device.zsh
