require('packer-install')
require('plugins.packer')
require('plugins.shortConfs')
require('plugins.closetag')
require('plugins.compe')
require('plugins.lsp')
require('plugins.lualine')
--require('plugins.syntastic')
require('plugins.telescope')
require('opts')
require('setup')
require('binds')
require('colourscheme')

